app = "dashi"
primary_region = "iad"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[env]
  RAILS_LOG_TO_STDOUT = "1"
  RAILS_SERVE_STATIC_FILES = "true"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[mounts]
  source = "dashi_storage"
  destination = "/rails/storage"
